### ISSUE TITLE
How to revert to default icons?

### ISSUE THREAD

**Issue by jej** [costales/folder-color#1]
Hi,
I uninstalled the extension. The folders with custom color icons are now white.
How is it possible to get the default theme for these icons? Where is stored information about icons?
Thx.

**Comment by jej** [comment]
Ok... I installed again, set default icon, and uninstalled.
Easy way :)
Thx.

**Comment by costales** [comment]
Hi,
Please, install it again and restore the icons, it will be the easy way.
The information is into the system, in the metadata. You could do it with a
script as:
gvfs-set-attribute myfolder -t unset metadata::custom-icon
Best regards.
--
Costales.
