### ISSUE TITLE
brz: ERROR: Already a branch: "folder-color". You not informed bzr of your Launchpad ID

### ISSUE THREAD

**Issue by vescovaccio** [costales/folder-color#10]
I moved to Ubuntu 20.10 and sorely missed Folder Colors with Yaru, so I tried installing from here. I cloned the Git repository, installed the dependencies, but "bzr branch lp:folder-color && cd folder-color && sudo python3 setup.py install --prefix=/usr" returns "You have not informed bzr of your Launchpad ID, and you must do this to write to Launchpad or access private data.  See "bzr help launchpad-login". brz: ERROR: Already a branch: "folder-color"."

Not sure if I did anything wrong ... Thanks!

**Comment by costales** [comment]
Hi,
Don't use the git repo, use the PPA:
https://www.omgubuntu.co.uk/2020/04/folder-colors-yaru-icon-update
Best regards.

**Comment by vescovaccio** [comment]
The ppa hasn't been updated for Ubuntu 20.10, that's why I tried to install from source. The link you give is for instructions relating to 20.04, not 20.10. I guess I'll have to be patient and wait for it to be pushed to 20.10. Thanks!

**Comment by costales** [comment]
Oh, I have to copy the PPAs. Could you try again the PPA?
Best regards.
--
Costales.
