### ISSUE TITLE
Cannot be installed on 20.10 (need to replace gvfs-bin dependency)

### ISSUE THREAD

**Issue by zilexa** [costales/folder-color#11]
Folder Color can no longer be installed on Ubuntu (Budgie) 20.10. It is dependent on gvfs-bin, but that no longer exists and cannot be installed. 
https://discourse.ubuntubudgie.org/t/backports-cannot-be-installed-on-20-10-lots-of-missing-applets/4460/6?u=zilexa

**Comment by zilexa** [comment]
Is folder-color not supported on 20.10 and 21.04?

**Comment by costales** [comment]
Hi,
It should be. Did you try to update it from backports repository?
Best regards.
--
Costales.

**Comment by magdesign** [comment]
Same issue here, tried to install on Ubuntu 22.04 from PPA.

But getting error about missing gvfs-bin (folder-color-nemo).
However, the installed version from PPA is still: 0.0.86

So I cloned your git repo and executed:
`sudo python3 setup.py install --prefix=/usr`

But still no folder color appears in nemo.
Any chance to update PPA or get detailed install instructions?
