### ISSUE TITLE
Update for Nautilus 43

### ISSUE THREAD

**Issue by jbicha** [costales/folder-color#17]
Nautilus 43.Beta.1 has been released with a major API change. Among other things, it has switched to GTK4.

nautilus-python 4.0.alpha has also been released with a major API change.

Please update folder-color so that it works with Nautilus 43.

Nautilus 43 is currently available in kinetic-proposed for Ubuntu 22.10 and nautilus-python 4 will be available there later today.

**Comment by jtojnar** [comment]
See also the migration guide: https://gnome.pages.gitlab.gnome.org/nautilus-python/nautilus-python-migrating-to-4.html

**Comment by costales** [comment]
Hi, thanks to @pakaoraki 's work this was fixed.
Please, could you confirm it is working (version 0.2.1)?
Thank you!

**Comment by laurento** [comment]
0.2.1 works flawlessly with Files 43 now ;)
Thanks!
