### ISSUE TITLE
Color applied is not instantly visible on symlinks

### ISSUE THREAD

**Issue by Coeur-Noir** [costales/folder-color#22]
Hi,

Ubuntu 22.10 here with Nautilus.

I've just installed : folder-color-common_0.1.3_all.deb and folder-color_0.2.7_all.deb

Log out / in session. It works but I need to refresh F5 or browse back and forth to see the change.

Expected ?

**Comment by costales** [comment]
Hi. It works for me. Please, remove all folder color, update apt and try to
install again. Common package should not be there.

**Comment by Coeur-Noir** [comment]
Ok, common has gone away.

And still same behaviour but you are right, colour is instantly applied on « natural » folders.

In my case, many folders are actually symbolic links and on those symbolic links the colour change is not seen instantly.
I assume it's more of a Nautilus behaviour here, not your « issue ».
If so, please confirm and I'll close here.

So, well, thank you very much !

**Comment by Coeur-Noir** [comment]
![folder-color-2210](https://user-images.githubusercontent.com/1895947/206826302-c6ac1f78-7da6-4713-aa55-cb1ea921a782.png)
I expected the « regular » folders from « installed » Yaru, as they already exist in many colors.

**Comment by costales** [comment]
Hi, yes, I can't do anything about that.
