### ISSUE TITLE
Are these the expected folders ?

### ISSUE THREAD

**Issue by Coeur-Noir** [costales/folder-color#23]
Hi ( again ),

it's more of a question than an issue, are these folders the expected ones in Ubuntu 22.04/22.10 ?
![folder-color-2210](https://user-images.githubusercontent.com/1895947/206826302-c6ac1f78-7da6-4713-aa55-cb1ea921a782.png)
I expected the « regular » folders from « installed » Yaru, as they already exist in 10 colors ( bark, sage, olive, orange, magenta, blue, purple and so on )
![example-with-default-yaru](https://user-images.githubusercontent.com/1895947/206870589-35899ebf-8fd1-4322-8255-acea7f08113f.png)

_____

If you like them, take them → https://github.com/Coeur-Noir/Yaru-folders-recolored
![folders_re-colored](https://user-images.githubusercontent.com/1895947/206828067-77910991-f567-4a85-8408-5f06efa67ffe.png)

**Comment by costales** [comment]
Hi, yes, those colors are the desired in the current release. I was
thinking into change them to the default Yaru colors, but Yaru is PNG and
doesn't have regular colors. And i don't see the folder so faster as with a
full color, then, probably they will stay like that by now, but thank you
so much for the feedback! Best regards

**Comment by Coeur-Noir** [comment]
Sorry, I have one icon that never matches, whatever size or color, _folder-*-download.png_ while it seems ok for all others.
![folder-recolored-download](https://user-images.githubusercontent.com/1895947/206869049-f5fcda8d-19da-4fb6-9ecf-1391d268d112.png)
…I did `sudo gtk-update-icon-cache /usr/share/icons/Yaru`
Logged out and in. Rebooted.
I can « manually » choose the icon ( right click on folder, properties, clic on icon, search in `/usr/share/icons/Yaru/…` )
Did I misspell some icon name ? _download_ or _download**s**_ ?

**Comment by costales** [comment]
Hi. It is downloads ;)
https://github.com/costales/folder-color/blob/master/README_THEME_SUPPORT

**Comment by Coeur-Noir** [comment]
Aaah… Original Yaru file is _folder-download.png_ without s hence my confusion..

Uuuff… some renaming to come, lol.

**Comment by Coeur-Noir** [comment]
Renaming done locally and in the repositories, now it works as expected !

Big thank you !

Please keep in mind that idea of symbolic links for using already existing assets ;-)

I close this issue.
