### ISSUE TITLE
Mint 21.1 (Beta) doesn't appear to support folder color changes

### ISSUE THREAD

**Issue by AlanAtOpcug** [costales/folder-color#24]
Just trying Folder Color for the first time after reading https://www.omgubuntu.co.uk/change-folder-color-ubuntu.  Installing folder-color-nemo only provides the option to add/change the emblem on any given folder.

![nemo_mint21 1](https://user-images.githubusercontent.com/109384173/208128978-835bf048-97dc-49ea-8ad7-2820fccea24c.png)

**Comment by costales** [comment]
Hi! I think you are using a theme not compatible with Folder Color. Which theme are you using and how did you install it? Thanks.

**Comment by AlanAtOpcug** [comment]
Thank you for the prompt response.  For icons, I am using the default Mint-Y theme.  You are correct that this issue is an incompatibility.  I checked several Mint themes and many provided only the option to modify the emblem.  However, one or two of the themes, e.g. breeze, allowed both the folder colour and the emblem to be changed.  I had thought that the problem might be related to the new (beta) version of Mint 21.1 but the same behaviour is exhibited by Mint 21.

**Comment by costales** [comment]
Hi,
Anyway, Linux Mint includes a fork of Folder Color preinstalled, you should
view a row of colors in Nemo.
Best regards.

**Comment by AlanAtOpcug** [comment]
Correct again.  But, the reason I tried Folder Color is that in the default Mint-Y theme the icon is a pale-yellow folder with a diagonal green line.  Changing the colour of the "folder" actually only changes the colour of the diagonal line.  However, this is also a function of the theme in use.  For example, the Mint-Y-Legacy theme allows the colour of the entire folder to be changed.

**Comment by costales** [comment]
Hi,
The Mint-Y appears not to support Folder Color extension:
```
$ find /usr/share/icons/Mint-Y -name *folder-blue*
$ 

```
Could you test it with another theme? As Numix, Papirus... Open this if they are not working either.
