### ISSUE TITLE
How to install on Vanilla OS

### ISSUE THREAD

**Issue by stpnwf** [costales/folder-color#26]
Hi, I would like to install folder-color on [VanillaOS](https://vanillaos.org/), an immutable Ubuntu-based distribution that uses [Distrobox](https://distrobox.privatedns.org/) to create containers where changes are overlayed on the system.

I would like to know if, given its implementation, folder-color can be installed this way on the system. 
Thanks in advance.

**Comment by costales** [comment]
Hi,
This works for Nautilus in any distro, but the PPA is for deb. If you want, you can run in it with these steps:
1. Install python3-nautilus
2. Create this file: /usr/share/nautilus-python/extensions/folder-color.py with this content: [GTK3 ](https://github.com/costales/folder-color/blob/master/nautilus-extension-gtk3/folder-color.py) or [GTK4](https://github.com/costales/folder-color/blob/master/nautilus-extension/folder-color.py).
3. Restart Nautilus with: nautilus -q
4. Use a [compatible theme](https://github.com/costales/folder-color/blob/master/README_THEME_SUPPORT).
A hug!
