### ISSUE TITLE
Folder color doesn't appear in nemo in ubuntu 22.10 despite working with nautilus

### ISSUE THREAD

**Issue by MTclement1** [costales/folder-color#29]
Hi,
I was using nautilus but it crashes and/or refuses to open so often that I decided to install nemo on my ubuntu 22.10. Nemo is working fine but not folder-color. It is installed but when starting nemo -q I get the error : 
** (nemo:561113): WARNING **: 13:06:06.309: Current gtk theme is not known to have nemo support (WhiteSur-Dark-solid-blue) - checking...
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/folder-color.py", line 16, in <module>
    gi.require_version("Gtk", "4.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Gtk is already loaded with version 3.0

The strange thing it that there is the same version check in the nautilus one, and when Nautilus agrees to work folder color is perfectly working. So I believe that Gtk4 is installed somewhere in the system.

Anyone has an idea as to why it doesn't work on nemo (and doesn't appear in plugin list either)?

**Comment by costales** [comment]
Hi,
Ubuntu 22.10 is obsolete, the updated package doesn't include it.
You need to install by hand the .deb package from another version, like the LTS:
https://launchpad.net/~costales/+archive/ubuntu/folder-color/+packages?field.name_filter=&field.status_filter=published&field.series_filter=jammy
Like this one (I don't remember if it needs a dependence):
https://launchpad.net/~costales/+archive/ubuntu/folder-color/+files/folder-color-nemo_0.3.0_all.deb
Best regards.
--
Costales.

**Comment by MTclement1** [comment]
Hi,
Thank you for your fast answer and solution.
On a unrelated note, I didn't know Ubuntu 22.10 was obsolete. I guess I have to keep moving forward and install 23.04 ? Would the package work ? I was kinda scared upgrading to 23.04 it would break many compatibility things, such as Nvidia pilot.

**Comment by costales** [comment]
You don't need to upgrade Ubuntu only for Folder Color. just uninstall all
folder color packages and install the .deb I said. It should be enough. If
not, ping me here

**Comment by costales** [comment]
As personal recomendation, install always the LTS versions, 22.04 now, it
has 5 years of support. Others have 6 months. The support is to have
updates. You can use your version, but change your repos to archive, then
you can install packages yet.

Did it work folder color from the deb?
Best regars

**Comment by MTclement1** [comment]
It worked perfectly with the older version !
I guess I should have taken 22.04 initially for downgrading without loosing everything is kinda impossible if I understand correctly.

**Comment by costales** [comment]
Downgrade is not possible. Use archive repos (search it) or upgrade to
22.04. Best regards
