### ISSUE TITLE
Can i build this with python3-nautilus instead of python2 ?

### ISSUE THREAD

**Issue by aduzsardi** [costales/folder-color#3]
When i install it on a ubuntu 20.04, it also installs python2 , python2-nautilus and some other python2 packages.
Can i instead use python3 packages ?

**Comment by aduzsardi** [comment]
I managed to install it manually by copying the the `nautilus-extension/folder-color.py` to `/usr/share/nautilus-python/extensions/` and installed Yaru-Colors

**Comment by costales** [comment]
Hi! Those packages are required by Nautilus, not by Folder Color. Best regards

**Comment by aduzsardi** [comment]
actually folder-color depends on `python-nautilus` , and in turn python-nautilus depends on libpython2.7

not sure if you can do and if else dependency management with debian packages to check if you are using python2 use python-nautilus as a dependency , and if you are uing python3 (ubuntu focal by default) use python3-nautilus as a dependency, or just create a separate package

**Comment by aduzsardi** [comment]
it turns out, you can do kind of an `or`

https://unix.stackexchange.com/a/44671

**Comment by costales** [comment]
Hi,
Honestly, IMHO the `folder-color` package is good. It's a Nautilus package issue, it should not require the python 2 (obsoleted).
Best regards.

**Comment by aduzsardi** [comment]
the problem is here -> https://github.com/costales/folder-color/blob/master/debian/control#L13
there's no python2-nautilus (at least not on debian/ubuntu) , all **python2** packages start with `python-` and all python3 packages start with `python3-` even if it's de default python version, so requiring python-nautilus , it actually requires python2

i don't expect you to change anything , i was able to install it just fine manually it works well (thanks btw) , just wanted to let you know of the behavior

**Comment by costales** [comment]
Hi, 
Thanks, I think you are right. I'll update the package.
Thanks Alex!

**Comment by costales** [comment]
Hi, 

Please, try the version `0.0.91` from the PPA:

```
sudo add-apt-repository ppa:costales/folder-color
sudo apt-get update
```

Thanks!

**Comment by lwbaqueros** [comment]
It works for me
Thanks

**Comment by costales** [comment]
You are welcome!
