### ISSUE TITLE
folders-colors-nautilus doesn’t start in Manjaro

### ISSUE THREAD

**Issue by jcsekinger** [costales/folder-color#33]
I have exactly the same problem in Manjaro, gnome 44.3, Nautilus 44.2.1, with folder-color-nautilus 0.3.2-1 in aur or folder-color-nautilus-git r42.61382f2-1. Is it identified ? fixed ? will it be fixed ? 
thank you
:)

_Originally posted by @jcsekinger in https://github.com/costales/folder-color/issues/28#issuecomment-1663414182_

**Comment by costales** [comment]
Hi!
Thank you for your feedback. But appears to be a Nautilus bug (?).
Best regards.
