### ISSUE TITLE
Cannot set custom icons Ubuntu 23.10

### ISSUE THREAD

**Issue by QuentiumYT** [costales/folder-color#35]
Hello, I'm having an issue with folder-color installed via the ppa. After restarting nautilus, I can provide the error:

```** Message: 09:46:53.251: Connecting to org.freedesktop.Tracker3.Miner.Files
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/folder-color.py", line 262, in _menu_activate_color
    self.foldercolor.set_color(item.get_location().get_path(), color)
  File "/usr/share/nautilus-python/extensions/folder-color.py", line 130, in set_color
    item_aux.set_attributes_from_info(info, 0, None)
gi.repository.GLib.GError: g-io-error-quark: Setting attribute metadata::custom-icon not supported (15)
```

I checked on Google but cannot find anything that could help.

Ubuntu 23.10 Mantic
Gio 2.77.3
GNOME nautilus 45.rc

**Comment by costales** [comment]
Hi,
Run a [command like this one](https://askubuntu.com/questions/1461288/gio-setting-attribute-metadatacustom-icon-not-supported) is returning something?

`gio info ~/Desktop`

Best regards.

**Comment by QuentiumYT** [comment]
Hi, sadly it says the same message as askubuntu: `gio: Setting attribute metadata::custom-icon not supported`

I have an other laptop with Ubuntu 23.10 as well and tried to install it, and it worked!

So I doubt there is an issue with my OS, every gio in path are the same, the output of gio info is approximately the same

<details><summary>Details</summary>
<p>

~ ❯ gio info ~/Desktop                                                                                                                                                                                     ⏎
display name: Desktop
edit name: Desktop
name: Desktop
type: directory
size:  4096
uri: file:///home/quentin/Desktop
local path: /home/quentin/Desktop
unix mount: /dev/nvme0n1p4 / ext4 rw,relatime,errors=remount-ro
attributes:
  standard::type: 2
  standard::is-hidden: FALSE
  standard::is-backup: FALSE
  standard::is-symlink: FALSE
  standard::name: Desktop
  standard::display-name: Desktop
  standard::edit-name: Desktop
  standard::copy-name: Desktop
  standard::icon: user-desktop, user-desktop-symbolic
  standard::content-type: inode/directory
  standard::fast-content-type: inode/directory
  standard::size: 4096
  standard::allocated-size: 4096
  standard::symbolic-icon: user-desktop-symbolic, user-desktop
  etag::value: 1697123575:178008:178008935
  id::file: l66308:6684719
  id::filesystem: l66308
  access::can-read: TRUE
  access::can-write: TRUE
  access::can-execute: TRUE
  access::can-delete: TRUE
  access::can-trash: TRUE
  access::can-rename: TRUE
  time::modified: 1697123575
  time::modified-usec: 178008
  time::access: 1698913237
  time::access-usec: 879999
  time::changed: 1697123575
  time::changed-usec: 178008
  time::created: 1635180723
  time::created-usec: 976609
  time::modified-nsec: 178008935
  time::access-nsec: 879999933
  time::created-nsec: 976609258
  time::changed-nsec: 178008935
  unix::device: 66308
  unix::inode: 6684719
  unix::mode: 16877
  unix::nlink: 2
  unix::uid: 1000
  unix::gid: 1000
  unix::rdev: 0
  unix::block-size: 4096
  unix::blocks: 8
  unix::is-mountpoint: FALSE
  owner::user: quentin
  owner::user-real: Quentin
  owner::group: quentin


</p>
</details> 

Finally I found that the working OS has a gio version of 2.78.0, and mine is currently 2.77.3, will try to update it. Do you know where this package comes from?

**Comment by QuentiumYT** [comment]
Interestingly enough, after an hour of research and tests, it looks like it's a problem with the gio installation (probably an external file messing or idk)

I did install glib into `/usr/local` first, and then `/usr` (bad idea most of the time but I had nothing to loose) and GIO is 2.78.1 but didn't worked. So I did exactly the same on my other computer (the one working), and it kept working with a custom build!
Lost myself in several deep issues and stackoverflow, and one guy gave me the idea of directly running the gio binary from the build folder and... IT DOES WORK

![image](https://github.com/costales/folder-color/assets/35229942/bb3e4c20-59ae-435b-9f23-341772f3d1c8)

So right now I have no clue what to do, I know that my system wide glib is broken (I have troubles with my Trash as well, just to mention that). Do you have any idea what I can do? Already tried to reinstall glib from official sources etc but looks like something is conflicting

**Comment by costales** [comment]
Hi! Thanks for your feedback!
I am not sure if it is a gnome issue or Linux. Probably a bug. Best regards

**Comment by QuentiumYT** [comment]
No clue, I will try to purge glib entirely and reinstall. Hopefully I do no break my OS 😅
I stumbled across several reports but it's probably a rare glib issue causing a few things to stop working, not related to Ubuntu or Gnome directly.
Thanks for your interrest anyway, I will close this issue because it has nothing to do with folder-colors :)
Btw, on my working OS, it looks really nice, thanks for this project!
Best regards
