### ISSUE TITLE
!NEED HELP AND GUIDANCE TO INSTALL ON LATEST VERSION OF DEBIAN 12! =NOT UBUNTU=

### ISSUE THREAD

**Issue by DEGENMUTANT** [costales/folder-color#42]
Heyy Costales i wanted to know if you have a full guided tutorial and instructions for installing 'folder-color' in the latest version of Debian 12, Ive done read all of your forums and other guided instructions for older versions of Debian but to no avail nothing seems to work ,  I know this url is old and the feed thread is old but i had to read it all to figure out the good and the bad https://answers.launchpad.net/folder-color/+question/692906 . It seems that Debian isnt compatible with some core features that Ubuntu automatically ships and i understand why.. But At least if Debian is going to say that they are the Father of Linux at least act like it, cause this doesn't make sense that from all these different articles and forums Ive been reading about Debian since currently just switched over from Ubuntu is heartbreaking to see spins and offsprings of Debian be better supported and maintained by their given supporters and communities... please help I really want to have 'folder-color' in Debian 12 like I had in Ubuntu, if not I'll just switch back to Ubuntu, seeing that the Father of Linux cant get their simple priorities in order. Thanks Costales. :)

**Comment by costales** [comment]
Hi!

I don't know what GTK version is using Debian 12, probably GTK4, then please, copy this file:

https://github.com/costales/folder-color/blob/master/nautilus-extension/folder-color.py

Here as: `/usr/share/nautilus-python/extensions/folder-color.py`

That should work. If not, try with the GTK3 version https://github.com/costales/folder-color/blob/master/nautilus-extension-gtk3/folder-color.py

Best regards.

**Comment by costales** [comment]
Hi!

I don't know what GTK version is using Debian 12, probably GTK4.

Just try this .deb: https://launchpad.net/~costales/+archive/ubuntu/folder-color/+files/folder-color_0.4.1_all.deb

Best regards.

**Comment by DEGENMUTANT** [comment]
Thanks for the fast reply , but im currently using, gtk-launch --version "3.24.38" which is almost close to GTK4. And I've already downloaded your latest version of Folder-color and tried installing it with the Software Installer from right-clicking but to no avail it failed..Costales

**Comment by DEGENMUTANT** [comment]
1. Installing with apt,   
sudo apt install ./folder-color_0.4.1_all.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'folder-color' instead of './folder-color_0.4.1_all.deb'
folder-color is already the newest version (0.4.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up folder-color (0.4.1) ...
gtk-update-icon-cache: No theme index file.
dpkg: error processing package folder-color (--configure):
 installed folder-color package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 folder-color
E: Sub-process /usr/bin/dpkg returned an error code (1)


2. Installing with nala, 

Error: Installation has failed.
If you'd like to file a bug report please include '/var/log/nala/dpkg-debug.log'

Error: error processing package folder-color (--configure):

Error: error processing package folder-color (--configure):
 installed folder-color package post-installation script subprocess returned error exit status 1
 installed folder-color package post-installation script subprocess returned error exit status 1

Errors were encountered while processing:
 folder-color

I also tried Software Installer too but that failed... Any other methods to try ?

**Comment by DEGENMUTANT** [comment]
Switching Back to Ubuntu Thanks for the help....gonna check out their new version that i just found :)

**Comment by costales** [comment]
Wait a bit. You can install in gtk 3 too. Can't reply how now

**Comment by costales** [comment]
Just copy this file:

https://github.com/costales/folder-color/blob/master/nautilus-extension-gtk3/folder-color.py

Into /usr/share/nautilus-python/extensions/

This code is GTK3.
Best Regards

**Comment by DEGENMUTANT** [comment]
Thanks but i already switched back to Ubuntu on there new 24 Noble release kinda like it so far with the new look and fell etc.. :)
