### ISSUE TITLE
Not compatibility when having nautilus-admin plugin installed

### ISSUE THREAD

**Issue by lwbaqueros** [costales/folder-color#5]
Just to let you know and to find a solution: If I have installed the plugin [nautilus-admin](https://github.com/brunonova/nautilus-admin) and then I want to install folder color through `sudo apt install folder-color` It deletes the nautilus-admin package. If you re-install the nautilus-admin plugging it uninstalls the folder-color plugin. I think nautilus-admin plugin has is not maintained anymore. Is there any solution for having folder-color alongside with nautilus-admin? 
I am on Ubuntu 20.04

1. Here is an example if I want to install both plugins: 
`sudo apt install nautilus-admin folder-color`

> Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 folder-color : Depends: python-nautilus but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

2. Here an example if _nautilus-admin_ is already installed and I want to install _folder-color_:
`sudo apt install folder-color`

>The following additional packages will be installed:
  python-nautilus
The following packages will be REMOVED:
  nautilus-admin python3-nautilus
The following NEW packages will be installed:
  folder-color python-nautilus
0 upgraded, 2 newly installed, 2 to remove and 30 not upgraded.

**Comment by costales** [comment]
Hi,

I'll move the dependencies to `python3-nautilus` because of #3 . I think that will fix this.

Best regards.

**Comment by costales** [comment]
Hi, 

Please, try the version `0.0.91` from the PPA:

```
sudo add-apt-repository ppa:costales/folder-color
sudo apt-get update
```

Thanks!

**Comment by lwbaqueros** [comment]
Not both are working well. thanks.
