### ISSUE TITLE
Sync translations from Launchpad

### ISSUE THREAD

**Issue by AsciiWolf** [costales/folder-color#8]
Please, consider syncing the translations from Launchpad. Many translations were updated since folder-color was migrated to GitHub. For example the Czech language that is now 100% translated on Launchpad, but remains partially translated in GitHub repo [po file](https://github.com/costales/folder-color/blob/master/po/cs.po).

**Comment by costales** [comment]
Hi,
I download the translations from Launchpad in each new release. Until there will be a new release, the translations will not be updated.
Best regards and thanks for the feedback!
